### ISSUE TITLE
find a way to reanimate connected iOS device which is not recognized by go ios utility

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#100]
as of now we just exit with status code 0 to avoid constant restart (#99).
but it would be great to find something similar to `usbreset` we have for android to reanimate device without physical reconnect.

think about usbmuxd containerization as seems like usbmuxd service restart fix the problem. the only negative side effect - all connected iOS devices will be reconnected on restart

**Comment by vdelendik** [comment]
we just exit with error code 1 now to initiate stf container restart... 
changes already applied on demo server. we have to find a way to emulate the problem.

**Comment by dhreben** [comment]
Verified.
