### ISSUE TITLE
ios: exit with status 0 if ios device is not accessible

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#113]
```
2022/12/12 16:35:22 socat[34] E getaddrinfo("appium", "NULL", {1,0,1,6}, {}): Name or service not known
{"err":"Failed getting devicelist: EOF","level":"fatal","msg":"failed getting device list","time":"2022-12-12T16:35:22Z"}
Device is not available!
```

**Comment by vdelendik** [comment]
still TBD as during appium crash/restart we might block automatic recovery

**Comment by vdelendik** [comment]
fixed in `public.ecr.aws/zebrunner/mcloud-device:2.4.7-beta3`. changes deployed on demo.zebrunner.farm.
if device is not available then we have to exit forcibly. as only iOS device reconnected we should restart it by `ios listen` logic.

during the testing we have to check the stability of the stf for iOS devices

**Comment by dhreben** [comment]
Will be check on prod
