### ISSUE TITLE
remove `--appium-port` and `--host` from cli (mostly iOS)

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#115]
we don't plan to show anymore direct static appium host and port via STF, so `--appium-port` and `--host` args not required anymore
details: https://github.com/zebrunner/stf/issues/234

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-device/pull/116

**Comment by vdelendik** [comment]
`--host` and STF_PROVIDER_HOST env var were restored to be able to support easily distributed environments...

**Comment by dhreben** [comment]
Verified by basic manually  acceptance and automatically with iOS device
