### ISSUE TITLE
investigate scrcpy to use for android video recording (including audio)

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#137]
[srccpy-help.txt](https://github.com/zebrunner/mcloud-device/files/12259329/srccpy-help.txt)
https://github.com/Genymobile/scrcpy

The Android device requires at least API 21 (Android 5.0).
Audio forwarding is supported for API >= 30 (Android 11+).

**Comment by azarouski** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/recording.md

**Comment by vdelendik** [comment]
closing as dupe of https://github.com/zebrunner/appium/issues/9
