### ISSUE TITLE
remove or use parametrize values for ios connect-app-dealer and connect-dev-dealer options

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#142]
https://github.com/zebrunner/mcloud-device/blob/eda7fdf95e75325a3a50308a23886d14d6b536a2/files/start_all.sh#L87C5-L87C104

**Comment by vdelendik** [comment]
doen, changes are available in `mcloud-device:2.5.1` on new mac only!

**Comment by dhreben** [comment]
Done Basic acceptance
