### ISSUE TITLE
revert #153

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#157]
in 2.5.3 we delivered smart verification of the go ios timed out case:
#153 exit 0 if go ios can't send a message to device

we did it as ipa install via stf doesn't work in such case. At the same time it blocks stf recovery and automation execution. let's revert this feature in upcoming 2.5.4 as installation ipa through UI is not a must in comparison with appium/xcuitest access

**Comment by dhreben** [comment]
Closed
