### ISSUE TITLE
port fixes for device type/class detection fix from appium

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#161]
https://github.com/zebrunner/mcloud-device/blob/46d3c656a8033fe646f5c35c1d600e03a2419031/files/start_all.sh#L53

take a look for reference: https://github.com/zebrunner/appium/issues/293

**Comment by vdelendik** [comment]
fix ported, it should appear in mcloud-device:2.6.1 soon

**Comment by dhreben** [comment]
Verified.
