### ISSUE TITLE
tcp connection verification doesn't support usage of ip addresses

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#192]
parsing `tcp //192.168.88.88:7250` is not supported, only DNS name usage is possible like
`tcp://demo.zebrunner.farm:7250`.

@azarouski, please review your parse logic to support usage of ip address
```
parse_url_for_nc() {
  # tcp://demo.zebrunner.farm:7250 -> demo.zebrunner.farm 7250
  echo "$1" | sed -nE 's/^([a-z]*:\/\/)*([a-z\.]+):([0-9]*)/\2 \3/pI'
}
```

**Comment by vdelendik** [comment]
grep cut using `:` as a separator might be the best option. let's review IPv6 use case also

**Comment by vdelendik** [comment]
fixed using `:` as separator

**Comment by dhreben** [comment]
Basic acceptance with iOS-Preferences-Test ,Mobile-iOS-Safari-Test , Android-Demo-Test successfully completed. Video, screenshots and logs are available.
