### ISSUE TITLE
try to reuse embedded stf vnc instead of websockify

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#58]
We use websockify to proxy vnc session outisde as we determine specific port and share it...
At the same time on port 5900 STF already start something similar and send images to `screen-port` when device open.

So let's investigate if we can use dynamic `screen-port` for automation when device occupied by automation only or maybe forward 5900 outside directly...

**Comment by vdelendik** [comment]
websockify and vncLink removed as of now starting from 2.0

**Comment by vdelendik** [comment]
@azarouski, in scope of new recording service for the mobile, please, share your findings with websocat to be able to start streaming in this ticket. It seems like we have to adjust reporting to be able to join correctly and show images stream instead of vnc

**Comment by azarouski** [comment]
done #199

**Comment by dhreben** [comment]
Basic acceptance with iOS-Preferences-Test ,Mobile-iOS-Safari-Test , Android-Demo-Test successfully completed. Video, and logs are available.
