### ISSUE TITLE
think about upgrading base ubuntu image to 18, 20 or 21

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#62]
as we split stf and appium we could try to jump into the latest ubuntu docker images

**Comment by vdelendik** [comment]
stf updated to ubuntu20: https://github.com/zebrunner/stf/pull/450
so mcloud-device automatically will be converted to it as well.

**Comment by dhreben** [comment]
Closed.

```
root@285....2b:/opt# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```
