### ISSUE TITLE
rename repo to device and think about numbering

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#68]
1.0 or 1.4 or 2.0 - TBD. Maybe clone existing repo with all the history into the new one to preserve old and new one

**Comment by vdelendik** [comment]
done. repository renamed to `mcloud-device`. next release will be 2.0 with appropriate milestone: https://github.com/zebrunner/mcloud-device/milestone/11

**Comment by dhreben** [comment]
Verified.
Repo is renamed to `Mcloud- device`
