### ISSUE TITLE
reuse usbreset feature for the problematic android containers

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#73]
from time to time we see that stf can't via db to device. we do kill and restart containers but without physical reconnect devices can't be connected correctly.
So let's improve mcloud-device healthcheck and integrate our own usbreset binary which emulate physical reconnect and guarantee that device is up&running

**Comment by vdelendik** [comment]
done. testing should be occur using mcloud-agent:develop branch.
test scenario should include as of now:
1. configure and start services
2. connect to bash to any mcloud-device container using `docker exec -ti device-Galaxy_A40-R...X bash`
3. do usbreset for registered device using this exact command: 
    ```
    usbreset ${DEVICE_BUS}`
    ```
-> emulation of usb reconnect should happen, all docker containers for device recreated and started successfully

**Comment by vdelendik** [comment]
in spite of the fact that rest is successful docker containers can't be re-created on prod envs

**Comment by vdelendik** [comment]
done

**Comment by dhreben** [comment]
Verified.
```
docker exec -ti device-Samsung_Tab_A7-R9.........X2J bash
stf@26e04cd57b9c:/opt$ usbreset ${DEVICE_BUS}
Resetting USB device /dev/bus/usb/003/011
```
run `docker ps -a`
**Expected result** : All docker containers for device recreated and started successfully
