### ISSUE TITLE
made appium docker state check as part of healthcheck

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#76]
there is no sense to keep stf container (android and ios) if appium container is exited.
such devices can't be used by automation (nothing is registered in grid) and manually - wda is not accessible.

in case of problem with appium container we have to exit from stf (mcloud-device) as well

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-device/pull/77

testing should be done using latest mcloud-agent; branch: develop.
suggested scenario (iOS):
1. login to appium container and kill appium process (repeat 3-4 times as we have 3 retries by default now in case of automatic reconnect) 
2. review stf mcloud-device healthcheck. it should have something like `[date] Appium container is unhealthy!`
-> state of the stf container should be Exited (potentially after 3 automatic retries)

**Comment by dhreben** [comment]
Verified.

`"Output": "Appium is unhealthy!\n"`
