### ISSUE TITLE
use WDA_ENV vars at once for provider startup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-device#91]
let's remove WDA_ENV file in mcloud-device right before stf ios-device startup as we already detected required data. Otherwise next restart on-failure don't wait till 1st wda session started. Also updated ip address of the device can't be handled correctly as old WDA_ENV is sued

**Comment by vdelendik** [comment]
fixed. during the testing we should kill wda inside iOS appium container and restart container...
-> device in STF will be available with a pause (upto 1-2m when 1st wda session started). Earlier right after docker container restart it appeared in STF asap in non operating state

**Comment by vdelendik** [comment]
reopening as provided rw permissions not enough

**Comment by vdelendik** [comment]
as an compromise we can do such steps:
1. reset file content before stf service startup
```
echo > ${WDA_ENV}
```
3. improve WDA_ENV file verification everywhere (appium , stf, mcloud-device etc?!).
in addition to file exists we have to check it's size and continue only of it is non zero

**Comment by vdelendik** [comment]
again uncommented reset as WDA_ENV file is not used anymore in appium healthcheck
changes are available in `zebrunner/mcloud-device:2.4-beta5`

**Comment by vdelendik** [comment]
implemented verification in better way as WDA_ENV still used a lot inside appium and stf...
mcloud-device is only reader for this file and analyze also if `WDA_CRASHED=true` is registered. if yes we continue to wait.
`WDA_CRASHED=true` is added by appium as only wda crashed: https://github.com/zebrunner/appium/issues/146

**Comment by dhreben** [comment]
Verified.
